version: '3'

services:

  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/home/node/app
  mysql:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./.docker/prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 12345
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    ports:
      - 3000:3000
